Traceback (most recent call last):
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/mackie3/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gray = imread('Images/pancake.jpg', as_gray=True)
gray = gray[:2000,:2000]
print(gray.shape)

plt.imshow(gray, cmap='gray')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/3d/s79lt6q910z0whw_7c_z48lc0000gp/T/ipykernel_11269/2135201396.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgray[0m [0;34m=[0m [0mimread[0m[0;34m([0m[0;34m'Images/pancake.jpg'[0m[0;34m,[0m [0mas_gray[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mgray[0m [0;34m=[0m [0mgray[0m[0;34m[[0m[0;34m:[0m[0;36m2000[0m[0;34m,[0m[0;34m:[0m[0;36m2000[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0mgray[0m[0;34m.[0m[0mshape[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mgray[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0;34m'gray'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/skimage/io/_io.py[0m in [0;36mimread[0;34m(fname, as_gray, plugin, **plugin_args)[0m
[1;32m     46[0m [0;34m[0m[0m
[1;32m     47[0m     [0;32mwith[0m [0mfile_or_url_context[0m[0;34m([0m[0mfname[0m[0;34m)[0m [0;32mas[0m [0mfname[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 48[0;31m         [0mimg[0m [0;34m=[0m [0mcall_plugin[0m[0;34m([0m[0;34m'imread'[0m[0;34m,[0m [0mfname[0m[0;34m,[0m [0mplugin[0m[0;34m=[0m[0mplugin[0m[0;34m,[0m [0;34m**[0m[0mplugin_args[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     49[0m [0;34m[0m[0m
[1;32m     50[0m     [0;32mif[0m [0;32mnot[0m [0mhasattr[0m[0;34m([0m[0mimg[0m[0;34m,[0m [0;34m'ndim'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/skimage/io/manage_plugins.py[0m in [0;36mcall_plugin[0;34m(kind, *args, **kwargs)[0m
[1;32m    205[0m                                (plugin, kind))
[1;32m    206[0m [0;34m[0m[0m
[0;32m--> 207[0;31m     [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    208[0m [0;34m[0m[0m
[1;32m    209[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py[0m in [0;36mimread[0;34m(*args, **kwargs)[0m
[1;32m      8[0m [0;34m@[0m[0mwraps[0m[0;34m([0m[0mimageio_imread[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;32mdef[0m [0mimread[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 10[0;31m     [0;32mreturn[0m [0mnp[0m[0;34m.[0m[0masarray[0m[0;34m([0m[0mimageio_imread[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py[0m in [0;36mimread[0;34m(uri, format, **kwargs)[0m
[1;32m    263[0m [0;34m[0m[0m
[1;32m    264[0m     [0;31m# Get reader and read first[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 265[0;31m     [0mreader[0m [0;34m=[0m [0mread[0m[0;34m([0m[0muri[0m[0;34m,[0m [0mformat[0m[0;34m,[0m [0;34m"i"[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    266[0m     [0;32mwith[0m [0mreader[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    267[0m         [0;32mreturn[0m [0mreader[0m[0;34m.[0m[0mget_data[0m[0;34m([0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/imageio/core/functions.py[0m in [0;36mget_reader[0;34m(uri, format, mode, **kwargs)[0m
[1;32m    170[0m [0;34m[0m[0m
[1;32m    171[0m     [0;31m# Create request object[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 172[0;31m     [0mrequest[0m [0;34m=[0m [0mRequest[0m[0;34m([0m[0muri[0m[0;34m,[0m [0;34m"r"[0m [0;34m+[0m [0mmode[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    173[0m [0;34m[0m[0m
[1;32m    174[0m     [0;31m# Get format[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/imageio/core/request.py[0m in [0;36m__init__[0;34m(self, uri, mode, **kwargs)[0m
[1;32m    122[0m [0;34m[0m[0m
[1;32m    123[0m         [0;31m# Parse what was given[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 124[0;31m         [0mself[0m[0;34m.[0m[0m_parse_uri[0m[0;34m([0m[0muri[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    125[0m [0;34m[0m[0m
[1;32m    126[0m         [0;31m# Set extension[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/imageio/core/request.py[0m in [0;36m_parse_uri[0;34m(self, uri)[0m
[1;32m    258[0m                 [0;31m# Reading: check that the file exists (but is allowed a dir)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    259[0m                 [0;32mif[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mfn[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 260[0;31m                     [0;32mraise[0m [0mFileNotFoundError[0m[0;34m([0m[0;34m"No such file: '%s'"[0m [0;34m%[0m [0mfn[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    261[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    262[0m                 [0;31m# Writing: check that the directory to write to does exist[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: No such file: '/Volumes/GoogleDrive/My Drive/GlacierStats/gstatsimbook/Images/pancake.jpg'
FileNotFoundError: No such file: '/Volumes/GoogleDrive/My Drive/GlacierStats/gstatsimbook/Images/pancake.jpg'

